# -*- coding: utf-8 -*-
"""python-for-finding-morse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P1HXCLn1uYOAM7eFT-nyTgy-LR6NIf-7
"""

import pandas as pd
import numpy as np

data = pd.read_csv(r"G:\My Drive\UALR\GA\GA\Repository\paraview\umap\data_sorted_label_enc_out.csv")

data

c = 0
d = 299
a = -14.0995
b = 24.0164

u_0_trx = c+(((d-c)/(b-a))*(data['UMAP-0']-a))

data['u_0_trx'] = u_0_trx

c = 0
d = 299
a = -14.8735
b = 23.5025

u_1_trx = c+(((d-c)/(b-a))*(data['UMAP-1']-a))
u_1_trx

data['u_1_trx'] = u_1_trx
data

morse_smalle_df = pd.read_csv(r"G:\My Drive\UALR\GA\GA\Repository\paraview\paraview_states\morse_smale-complex.csv")



data['u_0_trx'] = data['u_0_trx'].apply(np.floor)

data['u_1_trx'] = data['u_1_trx'].apply(np.floor)

result = pd.DataFrame(columns=['Point ID',	'Structured Coordinates:0',	'Structured Coordinates:1','Structured Coordinates:2',	'AscendingManifold',	'DescendingManifold',	'MorseSmaleManifold',	'SplatterValues',	'SplatterValues_Order'])
for row in data.itertuples():
   column1_value = row.u_0_trx
   column2_value = row.u_1_trx
   result = result.append(morse_smalle_df[(morse_smalle_df['Structured Coordinates:0'] == column1_value) & (morse_smalle_df['Structured Coordinates:1'] == column2_value) & (morse_smalle_df['Structured Coordinates:2'] == 1)],ignore_index=True)
# result.to_csv('filename.CSV', index=False)
  #  result.append(morse_smalle_df[(morse_smalle_df['Structured Coordinates:0'] == column1_value) & (morse_smalle_df['Structured Coordinates:1'] == column2_value)],ignore_index=True)
print(result)

data['AscendingManifold'] = result['AscendingManifold']
data['MorseSmaleManifold'] = result['MorseSmaleManifold']

data.to_csv(r"C:\Users\amohammed1\Downloads\morse_output_python.csv")
print("Successfully Created the csv files !!! ")